#!/bin/bash
# 
# docker-all-logs: List all containers and their logs, requiring a keypress to continue after each container.
# 
# Written in 2022 by Jon Clucas https://github.com/shnizzedy
# 
# To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
# You should have received a copy of the CC0 Public Domain Dedication along with this software. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
# 
# Usage: docker-all-logs

I=0
NUMBER_OF_CONTAINERS=$(expr $(docker ps | wc -l) - 1)
for CONTAINER in $(docker ps --format 'table {{.Names}}' | tail -n $NUMBER_OF_CONTAINERS)
do
  docker logs $CONTAINER
  I=$(expr $I + 1)
  if [ $I -lt $NUMBER_OF_CONTAINERS ]
  then
    read -n 1 -p "↑ $CONTAINER ↑"
  else
    echo "↑ $CONTAINER ↑"
  fi
done
